### ISSUE TITLE
change images CSS

### ISSUE THREAD

**Issue by niryariv** [Gizra/CDL#191]
``` css
div.cdl .flex {
    margin-left: 0;
}

div.cdl .flex img {
    max-width: 100%;
}

div.cdl .flex .box-1 .item-1 {
    margin-right: 10px;
}

div.cdl .box-wrapper-4 .box-2 .item-3 {
    min-width: 140px;
    margin-right: 10px;
    float: right;
}
```

remove `width: 520px;` at .item-1 and `width: 140px;` at .item-3
